<content class="test">
	<div  class="connect">
		<fieldset style=" margin-top: 3em; border-radius: 10px; font-size: 25px;">
			<legend><strong><em>Connexion</em></strong></legend>
				<form method="post" action="machat.php">
					<label style="margin-right: 5px;" id="username">Identifiant :</label><input style="border-radius: 7px; width: 20em; "type="text" name="username" placeholder="votre identifiant"><br><br>
					<label id="password" style="margin-right: 5px;">Mot de passe :</label><input style="border-radius: 7px; width: 15em;"  type="password" name="password" placeholder="votre mot de passe"><br><br>
					<input style="font-size: 15px;" type="submit" value="Connexion" name="connexion"> 
					<p style="font-size: 10px;"><a href="inscription.php"><em>Pas de compte ? ici pour s'inscrire !</em></a></p>
				</form>
		</fieldset>	
	</div>
	<div class="connect">
		<fieldset style=" margin-top: 3em; border-radius: 10px; font-size: 25px;">
			<legend><strong><em>Acheter sans se connecter</em></strong></legend>
				<form method="post" action="machat.php">
					<label style="margin-right: 5px;" id="username">Nom :</label><input style="border-radius: 7px; width: 20em; "type="text" name="username" placeholder="votre Nom"><br><br>
					<label id="prenom" style="margin-right: 5px;">Prénom :</label><input style="border-radius: 7px; width: 15em;"  type="text" name="prenom" placeholder="Votre Prénom"><br><br>
					<label id="adresse" style="margin-right: 5px;">Adresse de livraison :</label><input style="border-radius: 7px; width: 15em;"  type="text" name="Adresse" placeholder="Adresse de livraison"><br><br>
					<label id="ville" style="margin-right: 5px;">Ville :</label><input style="border-radius: 7px; width: 15em;"  type="text" name="ville" placeholder="Ville"><br><br>
					<label id="email" style="margin-right: 5px;">Email :</label><input style="border-radius: 7px; width: 15em;"  type="email" name="Email" placeholder="ex: maildeliraison@gmail.com"><br><br>
					<label id="tel" style="margin-right: 5px;">Téléphone :</label><input style="border-radius: 7px; width: 15em;"  type="tel" name="tel" placeholder="+33"><br><br>

					<input style="font-size: 15px;" type="submit" value="Finaliser mon achat" name="connexion"> 
				</form>
		</fieldset>	
	</div>
</content>








