
	<div style="text-align: center;">
		<fieldset style="margin-left: 15em; margin-right: 15em; margin-top: 2em; border-radius: 10px; font-size: 25px;margin-bottom: 10px;">
			<legend><strong>Billet pour la coupe du monde 2022 !!!</strong></legend>
				<a href="#"><img class="flotte" style="margin-right: 25px; margin-top: 20px;" src="img/billet.png"></a>

					<form method="post" action="achat.php" style="margin-left: 5px;">
						<p style="margin-top: 30px; padding-top: 35px;  line-height: px" class="p"></p>
						<label id="nombre"><strong>Nombre de billet :</strong></label>
							<select id="nombre" name="nombre de billet">
								<option value="1" >1</option>
								<option value="2" >2</option>
								<option value="3" >3</option>
								<option value="4" >4</option>
								<option value="5" >5</option>
							</select>
						<p><strong>Prix P VIP :</strong>&nbsp;&nbsp;1250* euros&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input style="font-size: 15px;" type="submit" value="Acheter" name="achat"></p>
						<p><strong>Prix P  normal :</strong>&nbsp;&nbsp;120** euros&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input style="font-size: 15px;" type="submit" value="Acheter" name="achat"></p>
					</form>
		</fieldset>
		<p>* Ce prix comprend une place dans la tribune VIP ou présidentielle, un accueil privélégié et une coupe de champagne.</p>
		<p>** Ce prix comprend une place standard.</p>
	</div>


