<!DOCTYPE html>
<html>
<head>
	<title>Contact</title>
</head>
<body>
	<fieldset style="margin-left: 15em; margin-right: 15em; margin-top: 5em; border-radius: 10px; font-size: 25px;">
			<legend><strong><em>Nous contacter</em></strong></legend>
				<form method="post">
					<label id="nom">Nom :</label><input type="text" name="nom" id="nom"><br>
					<label id="nom">Prenom :</label><input type="text" name="nom" id="nom"><br>
					<label id="mail">Email :</label> <input type="email" name="mail" id="mail"><br>
					<label id="tel">Téléphone :</label><input type="tel" name="tel"><br><br>

					<textarea placeholder="255 caractères max" style="width: 500px; height: 150px;"></textarea>
					<br>
					<input type="submit" name="Envoyer" value="Envoyer"> <input type="reset" name="reset" value="Effacer"><br>
					
				</form>
	</fieldset>
	<br>
	<br>
	<br>










</body>
</html>