<div class="page_acceuil">
	<div class="solo">
		<h2 class="soloq">OBJECTIF 2022 ! <h2>
		<img class="soloz" src="img/Coupe.png">
	</div>
	<div class="flex2">
		<h3><b>Planet Soccer ?</b></h3>
		<h4>-Entreprise de vente de maillots Euro 2016 et 2018.</h4>
		<h4>-Statstiques sur les équipes de l'Euro 2016 (classement et joueurs par équipes)</h4>
		<h4>-Objectif de devenir la 1re entreprise de vente de maillots.</h4>
		<h4>-Chiffre d'affaires annuel : 20 Millions d'euros. </h4>
	</div>
</div>