
	<form class="inscription" method="post" action="seconnecter.php">
		<fieldset style="margin-left: 15em; margin-right: 15em; margin-top: 3em; border-radius: 10px; font-size: 20px;">
			<legend><em><strong>Inscription</strong></em></legend>
			<p>- <em  style="text-decoration: underline; font-size: 20px;">Information personnelle :</em></p>
				<label id="nom">Nom :</label><input placeholder="Nom" type="text" name="nom">
				<br><br>
				<label id="prenom">Prénom :</label><input placeholder="ex: Patrick" type="text" name="prenom">
				<br><br>
				<label id="date">Date de naissance :</label><input type="date" name="date">
				<br><br>
				<label id="adresse">Adresse :</label><input placeholder="adresse" type="text" name="adresse">
				<br><br>
				<label id="mail">Adresse mail :</label><input placeholder="ex: test@test.com" type="email" name="mail">
				<br><br>
				<label id="tel">numéro de téléphone :</label><input placeholder="+33xxxxxxx" type="tel" name="tel">
				<br>
				<br>
		</fieldset>		

		<fieldset style="margin-left: 15em; margin-right: 15em; margin-top: 1em; border-radius: 10px; font-size: 20px;">
			<p>- <em  style="text-decoration: underline; font-size: 20px;">Information de connexion :</em></p>
			<label id="user">Pseudo :</label><input placeholder="ex: patrick04" type="text" name="user">
			<br><br>
			<label id="mdp">Mot de passe :</label><input placeholder="mot de passe" type="password" name="mdp">
			<br><br>
			<label id="mdp2">Confirmation du mot de passe :</label><input placeholder="*************" type="password" name="mdp2">
			<br><br>
			<span style="margin: auto;"><input type="submit" name="inscription" value="Inscription"><input type="reset" name="reset" value="Réinitialiser"></span>
			<br>
			<br>
		</fieldset>











	</form>






