
	<section style="margin-top: 20px; margin-left: 15em;">
		<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Le maillot de l'équipe <strong style="text-decoration: underline;">d'Irlande du Nord</strong></p>
			<a href="#"><img class="flotte" style="float: left; margin-right: 25px;" src="img/irlandeN.png"></a>
				<form method="post" action="achat.php" style="margin-left: 5px;">
					<div  style="margin-top: 7em;">
						<label id="taille"><strong>Taille :</strong></label>
						<select id="taille" name="Taille">
								<option value="1" >XS</option>
								<option value="2" >S</option>
								<option value="3" >M</option>
								<option value="4" >L</option>
								<option value="5" >XL</option>
								<option value="6" >XXL</option>
							</select>
							<br>
							<br>
						
						<label for="flocage" id="flocage"><strong>Flocage :</strong></label><input placeholder="nom..." type="text" name="flocage" id="flocage">
						<br>
						<br>

						<label for="flocage" id="num"><strong>Numéro du maillot :</strong></label><input placeholder="numéro de joueur" type="tel" name="flocage" id="num">
						<p><strong>Prix :</strong>&nbsp;&nbsp;150 euros</p>
						<input style="font-size: 15px;" type="submit" value="Acheter" name="achat">
						<br>
						<br>
						<br>
						<br>
						<br>
					</div>
				</form>
	</section>


	<section style="margin-top: 20px; margin-left: 15em;">
			<a href="#"><img class="flotte" style="float: left; margin-right: 25px;" src="img/irlandeN.png"></a>
				<form method="post" action="#" style="margin-left: 5px;">
					<p style="margin-top: 50px; padding-top: 35px;" class="p"><strong>Taille :</strong></p>
						<input type="checkbox" name="taille1" style="margin-right: 5px;" id="taille1"><label class="p" for="taille1">XS</label>
						<label for="taille2"></label><input  type="checkbox" name="taille2" id="taille2"><label  class="p" for="taille2">S</label>
						<label for="taille3"></label><input  type="checkbox" name="taille3" id="taille3"><label  class="p" for="taille3">M</label>
						<label for="taille4"></label><input  type="checkbox" name="taille4" id="taille4"><label  class="p" for="taille4">L</label>
						<label for="taille5"></label><input  type="checkbox" name="taille5" id="taille5"><label  class="p" for="taille5">XL</label>
						<label for="taille6"></label><input  type="checkbox" name="taille6" id="taille6"><label  class="p" for="taille6">XXL</label>
						<br>
						<br>
					
					<label for="flocage" id="flocage"><strong>Flocage :</strong></label><input placeholder="nom..." type="text" name="flocage" id="flocage">
					<br>
					<br>

					<p><strong>Prix :</strong>&nbsp;&nbsp;80 euros</p>
					<br>
					<input style="font-size: 15px;" type="submit" value="Acheter" name="achat">
					<br>
					<br>
					<br>
					<br>


				</form>
	</section>


