	<script src="https://www.google.com/recaptcha/api.js?render=_reCAPTCHA_site_key"></script>
	<div class="space">
		<h3>Choissisez le/les maillot(s) que vous souhaitez</h3>
		<div class="lines">
			<figure>
				<a href="france.php"><img class="flotte" src="img/france.png"></a>
			</figure>
			<figure>
				<a href="albanie.php"><img src="img/albanie.png"></a>
			</figure>
			<figure>
				<a href="allemagne.php"><img src="img/allemagne.png"></a>
			</figure>
			<figure>
				<a href="angleterre.php"><img src="img/angleterre.png"></a>
			</figure>
		</div>
		<div class="lines">
			<figure>
				<a href="autriche.php"><img src="img/autriche.png"></a>
			</figure>
			<figure>
				<a href="belgique.php"><img src="img/belgique.png"></a>
			</figure>
			<figure>
				<a href="croatie.php"><img src="img/croatie.png"></a>
			</figure>
			<figure>
				<a href="ecosse.php"><img src="img/ecosse.png"></a>
			</figure>
		</div>
		<div class="lines">
			<figure>
				<a href="espagne.php"><img src="img/espagne.png"></a>
			</figure>
			<figure>
				<a href="hongrie.php"><img src="img/hongrie.png"></a>
			</figure>
			<figure>
				<a href="irelande.php"><img src="img/irelande.png"></a>
			</figure>
			<figure>
				<a href="irelanden.php"><img src="img/irelandeN.png"></a>
			</figure>
		</div>
		<div class="lines">
			<figure>
				<a href="islande.php"><img src="img/islande.png"></a>
			</figure>
			<figure>
				<a href="italie.php"><img src="img/italie.png"></a>
			</figure>
			<figure>
				<a href="norvege.php"><img src="img/norvege.png"></a>
			</figure>
			<figure>
				<a href="pologne.php"><img src="img/pologne.png"></a>
			</figure>
		</div>
		<div class="lines">
			<figure>
				<a href="portugal.php"><img src="img/portugal.png"></a>
			</figure>
			<figure>
				<a href="roumanie.php"><img src="img/roumanie.png"></a>
			</figure>
			<figure>
				<a href="russie.php"><img src="img/russie.png"></a>
			</figure>
			<figure>
				<a href="serbie.php"><img src="img/serbie.png"></a>
			</figure>
		</div>
		<div class="lines">
			<figure>
				<a href="suede.php"><img src="img/suede.png"></a>
			</figure>
			<figure>
				<a href="suisse.php"><img src="img/suisse.png"></a>
			</figure>
			<figure>
				<a href="turquie.php"><img src="img/turquie.png"></a>
			</figure>
			<figure>
				<a href="ukraine.php"><img src="img/ukraine.png"></a>
			</figure>
		</div>

	</div>

	