
	<div class="seconnecter" style="text-align: center;">
		<fieldset style="margin-left: 15em; margin-right: 15em; margin-top: 5em; border-radius: 10px; font-size: 25px;">
			<legend><strong><em>Connexion</em></strong></legend>
				<form method="post" action="home.php">
					<label style="margin-right: 5px;" id="username">Identifiant :</label><input style="border-radius: 7px; width: 20em; "type="text" name="username" placeholder="votre identifiant"><br><br>
					<label id="password" style="margin-right: 5px;">Mot de passe :</label><input style="border-radius: 7px; width: 15em;"  type="password" name="password" placeholder="votre mot de passe"><br><br>
					<input style="font-size: 15px;" type="submit" value="Connexion" name="connexion"> 
					<p style="font-size: 10px;"><a href="inscription.php"><em>Pas de compte ? ici pour s'inscrire !</em></a></p>
				</form>
		</fieldset>	
	</div>










