
	<section style="margin-top: 20px; margin-left: 15em;">
		<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Le maillot de l'équipe <strong style="text-decoration: underline;">l'Ukraine</strong></p>
			<a href="#"><img class="flotte" style="float: left; margin-right: 25px;" src="img/ukraine.png"></a>
				<form method="post" action="achat.php" style="margin-left: 5px;">
					<div  style="margin-top: 7em;">
						<label id="taille"><strong>Taille :</strong></label>
						<select id="taille" name="Taille">
								<option value="1" >XS</option>
								<option value="2" >S</option>
								<option value="3" >M</option>
								<option value="4" >L</option>
								<option value="5" >XL</option>
								<option value="6" >XXL</option>
							</select>
							<br>
							<br>
						
						<label for="flocage" id="flocage"><strong>Flocage :</strong></label><input placeholder="nom..." type="text" name="flocage" id="flocage">
						<br>
						<br>

						<label for="flocage" id="num"><strong>Numéro du maillot :</strong></label><input placeholder="numéro de joueur" type="tel" name="flocage" id="num">
						<p><strong>Prix :</strong>&nbsp;&nbsp;150 euros</p>
						<input style="font-size: 15px;" type="submit" value="Acheter" name="achat">
						<br>
						<br>
						<br>
						<br>
						<br>
					</div>
				</form>
	</section>

